### ISSUE TITLE
Fate alerts (cross zone/server)

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#10]
### Description
Fate alerts across zones/servers.

### More info
As you can't track fates for a zone you're not in, this would need to use crowd-sourced data.
See https://discord.com/channels/581875019861328007/685275026156683280/756202265106448526 for more information.

Original requester: `Das#8008`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by SlyAceZeta** [comment]
Done, fulfilled by [Sonar](https://discord.gg/K7y24Rr)
