### ISSUE TITLE
Disable FATE music

### ISSUE THREAD

**Issue by TheGokki** [goatcorp/suggestions#1000]
### Plugin Description

A plugin that turns off FATE music, whenever it starts playing when entering a FATE, and plays the regular zone music as usual.

I want to disable this so i can enjoy the zone music without interruption from random fates around. It kills the mood & vibe.

### More info

This should disable both the announcement and the combat music (perhaps a toggle for each?).
Maybe add a toggle to include Boss FATEs, since those have a different music and makes sense to listen to separately from regular FATEs.
Perhaps this should go into SimpleTweaks... I hope this is easy enough to implement?

### Request Terms

- [X] I checked if this request wasn't already proposed
- [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by Rietty** [comment]
Is the default option not sufficient? I believe this is what you want?

![image](https://user-images.githubusercontent.com/35241556/231260194-d5202f3f-287b-4330-95b5-3bbdfa9bba89.png)

**Comment by slotthhy** [comment]
Boss fates do not adhere to that setting. @TheGokki You can accomplish this by using Orchestrion and setting a replacement for the particular FATE music you want to replace. Just set the replacement to "do not change BGM"

**Comment by TheGokki** [comment]
> Boss fates do not adhere to that setting. @TheGokki You can accomplish this by using Orchestrion and setting a replacement for the particular FATE music you want to replace. Just set the replacement to "do not change BGM"

This worked... partially. While Orchestrion does work to disable FATE music, it doesn't remove the starting zinger. So with Sound Filter i found the specific sound and blacklisted it too. The game also fades out the zone music when this happens so that's not something i can fix right now.

So end result is: i was able to suppress the FATE music and zinger, but not the brief fade out. And it does require some work to set it up. I guess i can close this for now but would still be nice to have that as a setting toggle somewhere so i wouldn't have to use two plogons just for this.
