### ISSUE TITLE
Sticker Note

### ISSUE THREAD

**Issue by velvetcarpets** [goatcorp/suggestions#1019]
### Plugin Description

A sticky note for players that is always visible, or appears on hover.

### More info

Functions akin to Chat Bubbles or other active player information that is always visible or has toggles for visibility. The sticky note would be entered from a window with input up to 30 characters and only visible to the player who set it. This can be applied to any player from any shared Data Center.
![ren](https://github.com/goatcorp/suggestions/assets/158850410/c50568e6-16ef-4ab5-ab1c-a913b41b0a0a)

### Request Terms

- [X] I checked if this request wasn't already proposed
- [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by GayPotatoEmma** [comment]
Hi, have you checked out either PlayerTrack or Honorific? They would be able to do similar things to fulfill this purpose.

PlayerTrack will let you assign Tags and Categories to players and you can also give them custom titles to reflect those.  
![Screenshot 2024-02-04 220630](https://github.com/goatcorp/suggestions/assets/153868115/a1b96101-af64-4692-ac5b-ac72aaf2df08)

Honorific will do a similar thing with the titles but will also only do that, and is a more lightweight solution. 
![Screenshot 2024-02-04 221029](https://github.com/goatcorp/suggestions/assets/153868115/26a6fb5c-c8d0-40af-aedc-8db4a366ad92)


These may satisfy your needs until a different solution shows up so I would recommend checking them out.

**Comment by velvetcarpets** [comment]
> Hi, have you checked out either PlayerTrack or Honorific? They would be able to do similar things to fulfill this purpose.

I'll try Honorific. I thought it was just a title editor for pre-existing player titles that could be seen by others. This one specifically would be private and a lot like Mare's active download box that appears beneath players so as not to override the game titles themselves.

Edit: I didn't mean to close the topic and I don't know how to re-open it. Oops.

**Comment by GayPotatoEmma** [comment]
> I thought it was just a title editor for pre-existing player titles that could be seen by others.

Nope, Honorific just like any other plugin is only visible to you and the titles do not override the existing titles, they're fully personal to the person
