### ISSUE TITLE
Combat Abilities/Weapon Skills outside of combat.

### ISSUE THREAD

**Issue by Maelien** [goatcorp/suggestions#1022]
### Plugin Description

This is a plugin that would help with the immersion of combat RP for those who engage in it.

### More info

When paired with Mare, the ability to use weapon skills or abilities outside of combat, it will bring a new layer to combat RP or shenanigans not seen elsewhere. This would also work into transformations (Enshroud) without the prerequisites.

This would also be handy in testing out certain VFX mods also, in the case that you're working on a project and need to fine tune it without the hassle of waiting on cooldowns or requirements from other skills.

I wanted to put this idea out there in case if it _was_ possible, but it would be a neat thing to see make happen. I am no coder by any means but if this idea sparks inspiration for something, that is fine too. ♥

### Request Terms

- [X] I checked if this request wasn't already proposed
- [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by reiichi001** [comment]
If it requires the use of an unsupported plugin from a custom repository, it's not likely to qualify as passing the plugin guidelines.

**Comment by Maelien** [comment]
> If it requires the use of an unsupported plugin from a custom repository, it's not likely to qualify as passing the plugin guidelines.

Ah, nevermind then. I am not sure where such ideas could go.
