### ISSUE TITLE
Paissa House adding favorites

### ISSUE THREAD

**Issue by Kogitsunism** [goatcorp/suggestions#1024]
### Plugin Description

Hello, I was wondering if Paissa house could add a favorites/like tab onto the [website](https://zhu.codes/paissa) for people so that they can track plots that they really liked. If there was a way to do so in game as well that would also be really nice, but I'm not sure how anybody would go about trying to do that. Thank you for your hard work and have a great day!

### More info

For example there are 37 houses up for sale, 15 being in the districts you like and Emp has 7 in all different locations of the wards but you really liked the location of 4 of them but now you cant quite remember which ones were the ones that you liked because you had to get up to go make dinner for the family or go to work,

### Request Terms

- [X] I checked if this request wasn't already proposed
- [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by ArcaneDisgea** [comment]
Hello! This repository is for suggestions for new plugins. If your suggestion is for an already existing plugin it would be better to reach out in the [Discord](https://discord.gg/holdshift) or by using the feedback button on the plugin in the in-game plugin installer.
