### ISSUE TITLE
Wuk Lamat deleter

### ISSUE THREAD

**Issue by agitusera** [goatcorp/suggestions#1029]
### Plugin Description

A plugin that either changes wuk lamats voice to one of the language options other than English or mutes her all together permanently, I'd ideally still like to keep all the other voices in english

### More info

pretty self explanatory, terrible unacceptable voice actor, single hand-idly ruined dawntrail for myself and many other people, the character is unfortunately terribly written but no plugin or addon can unfortunately fix that so muting her or allowing us to listen to her in another language to make it slightly more tolerable is preferable, hope this can be done so me and my friends don't have to endure her for future patches

much love from us

### Request Terms

- [X] I checked if this request wasn't already proposed
- [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by goaaats** [comment]
Don't think so
