### ISSUE TITLE
Set alias for in-game commands

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#105]
### Description
The ability to set aliases for commands, for example, I'm constantly accidentally typing /farewell instead of /goodbye, I would love to be able to set an alias so both work, being able to set /hi for /greet, etc etc.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/761056964309811212 for more information.

Original requester: `Dale#1707`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Real old suggestion. Been implemented for a long time now
