### ISSUE TITLE
Check all house spots

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#11]
### Description
Check all free house spots across all wards/subdivisions.

### More info
This would be a fit for the PaissaHouse plugin but would require crowd-sourcing the data.
See https://discord.com/channels/581875019861328007/685275026156683280/756256030421417985 for more information.

Original requester: `Akurosia Kamo#0666`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by SlyAceZeta** [comment]
Done, fulfilled by [PaissaHouse](https://github.com/zhudotexe/FFXIV_PaissaHouse)
