### ISSUE TITLE
Add status timers to party list

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#115]
### Description
Add status timers to party list.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/763245058924478464 for more information.

Original requester: `Zep#0138`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by Aireil** [comment]
+1

![Would look nice](https://i.imgur.com/iRfHZ4g.png)

**Comment by Caraxi** [comment]
I will do this

**Comment by nyxalteria** [comment]
can be marked as completed
