### ISSUE TITLE
Keybind to copy item name on mouseover

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#121]
### Description
Keybind to copy item name on mouseover (e.g. CTRL+C).

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/764951850872078387 for more information.

Original requester: `Sivil#8439`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Exists in SimpleTweaks
