### ISSUE TITLE
Skyrim compass

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#123]
### Description
A compass like Skyrim and Co., allowing one to disable the minimap but still get the basic direction for quest objectives.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/765920749281083402 for more information.

Original requester: `Chivalrik#9740`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by fitzchivalrik** [comment]
I am trying to produce something.  
Cannot promise success though.

**Comment by fitzchivalrik** [comment]
Implemented in https://github.com/fitzchivalrik/compass
