### ISSUE TITLE
Make NPCs refer to character using surname

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#128]
### Description
Make NPCs refer to player character exclusively by their surname.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/766163320881283072 for more information.

Original requester: `kirby#1208`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Already part of PrefPro
