### ISSUE TITLE
Extended stats information

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#140]
### Description
Show a pane with additional calculated rates and whatnot.

### More info
Example:
![Stats window example](https://cdn.discordapp.com/attachments/685275026156683280/751929181922656326/unknown.png)

See https://discordapp.com/channels/581875019861328007/685275026156683280/751929183793577995 for more information.

Original requester: `Hikarin#0208`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by SlyAceZeta** [comment]
Done, fulfilled by [Character Panel Refined](https://github.com/Kouzukii/ffxiv-characterstatus-refined)
