### ISSUE TITLE
Combo drop timer

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#145]
### Description
See title.

### More info
See https://discordapp.com/channels/581875019861328007/685275026156683280/753354581303623741 for more information.

Original requester: `Vie#0100`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by NadyaNayme** [comment]
This was added to Simple Tweaks.

`SimpleTweaks -> UI Tweaks -> Combo Timer`
