### ISSUE TITLE
Lock any plugin window in place

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#146]
### Description
See title.

### More info
See https://discordapp.com/channels/581875019861328007/685275026156683280/753693781181857812 for more information.

Original requester: `Dajova#6140`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by karashiiro** [comment]
This should probably be transferred to Dalamud, actually.

**Comment by nyxalteria** [comment]
also in simple tweaks
