### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#149]
### Description
See title.

### More info
See https://discordapp.com/channels/581875019861328007/685275026156683280/755171938711896186 for more information.

Original requester: `秘密の闇#0001`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by kalilistic** [comment]
Implemented in Wotsit.
