### ISSUE TITLE
Change player name color in chat messages

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#16]
### Description
Change the name of the player speaking in chat and allow to be different from the channel color.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/756506770029150279 for more information.

Original requester: `Azure#2392`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by karashiiro** [comment]
Adding "An option to change the color of the names in your chat window. Allowing you to also add specific colors to specific people."

**Comment by kalilistic** [comment]
Another variation requested for showing party members in a different color: https://discord.com/channels/581875019861328007/685275026156683280/854073192586674196

**Comment by SlyAceZeta** [comment]
Done, fulfilled by [PlayerTags](https://github.com/Pilzinsel64/PlayerTags)
