### ISSUE TITLE
Show release date in item tooltips

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#160]
### Description
"Is there a plugin for showing item level (ilvl) or patch release for everything? That would help my sanity in sorting random retainer venture results, for example."

The title is how I'm interpreting this.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/775876488637317160 for more information.

Original requester: fiive#3250

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by SlyAceZeta** [comment]
Done, fulfilled by [Which Patch Was That?](https://github.com/Kouzukii/ffxiv-whichpatchwasthat)
