### ISSUE TITLE
Disable types of chat like say and shout in individual zones

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#164]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/776780834342043708 for more information.

Original requester: Mysterious#5425

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by SlyAceZeta** [comment]
Duplicate of #139
