### ISSUE TITLE
Show distance to a target

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#167]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/778019991927914538 for more information.

Original requester: Eternita#4037

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by kalilistic** [comment]
Requested to show on nameplate: https://discord.com/channels/581875019861328007/685275026156683280/919223500449931265

**Comment by PunishedPineapple** [comment]
In-progress as the basis for https://github.com/goatcorp/suggestions/issues/742.  Will look into nameplates at some point; not sure how feasible it will be to add a text node to the nodes in that addon?

**Comment by PunishedPineapple** [comment]
"Distance" plugin for this is available in testing.  Nameplates are a planned feature, but not yet working.
