### ISSUE TITLE
Daily/weekly quest list

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#170]
### Description
Complete list of weeklies and dailies and their current progress/status that automatically updates (if possible) instead of them scattered all over.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/779311829091614740 for more information.

Original requester: Ruki#4576

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by kalilistic** [comment]
Daily Duty has been released.
