### ISSUE TITLE
Restrict ground targets to max range

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#171]
### Description
Restricting ground targets (e.g., Shukuchi, Salted Earth) to max range so if you click outside it goes as far as possible in that direction.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/779311829091614740 for more information.

Original requester: Ruki#4576

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by NadyaNayme** [comment]
This is now an in-game setting found under:

`Character Configuration -> Target -> [ ] Limit ring movement to targeting range.`
