### ISSUE TITLE
Show the name of whatever track is playing

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#172]
### Description
A simple plugin that merely shows the name of whatever track is playing, optionally only shows it for a few seconds when the track changes.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/779366344730083380 for more information.

Original requester: Tzarnal#7789

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Already in the Orchestrion Plugin. Shows song name in chat.
