### ISSUE TITLE
Display player names of people in your FC in a different colour

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#173]
### Description
A plugin that displays player names of people in your FC in a different colour similarly to how the game already does for party members and friends.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/779366344730083380 for more information.

Original requester: Tzarnal#7789

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by karashiiro** [comment]
Also https://discord.com/channels/581875019861328007/685275026156683280/795116014211170314

**Comment by johnysandels** [comment]
this suggestion [https://github.com/goatcorp/suggestions/issues/189](url) could be added to this.

**Comment by karashiiro** [comment]
This is the older one, closing this one instead

**Comment by karashiiro** [comment]
Wait, other way around.

**Comment by WesselKuipers** [comment]
I've been working on this over the weekend and I'm just about ready to have others test it.

I'll make a PR for this later tomorrow.

**Comment by WesselKuipers** [comment]
It's now in testing, let me know if there any issues that pop up.

https://github.com/goatcorp/DalamudPlugins/pull/853

**Comment by WesselKuipers** [comment]
Plugin should be available now!

https://github.com/goatcorp/DalamudPlugins/tree/master/plugins/FCNameColor
