### ISSUE TITLE
Make the text for chatlog smaller than 12

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#176]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/779985439959941130 for more information.

Original requester: JohnySandels#6820

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by SlyAceZeta** [comment]
Done, fulfilled by [Simple Tweaks Plugin](https://github.com/Caraxi/SimpleTweaksPlugin) (Chat Tweaks > Improved Font Sizes)
