### ISSUE TITLE
Circular gcd bar going around the mouse cursor

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#180]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/781308660290813972 for more information.

Original requester: ripdog#5124

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Already suggested [https://github.com/goatcorp/suggestions/issues/283](url)
