### ISSUE TITLE
Disable VFX entirely

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#182]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/782932314669187094 for more information.

Original requester: Dale#1707

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by lmcintyre** [comment]
I would tag this with research needed, to ensure that this doesn't have any side effects, like changing instance weather or changing enemy/player models.

**Comment by SlyAceZeta** [comment]
Possibly fulfilled by [EasyEyes](https://github.com/0ceal0t/EasyEyes)?
