### ISSUE TITLE
Filter specific ambient sounds

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#187]
### Description
Filter only certain ambient sounds. For example, you could mute background noise from people in Limsa but maintain bird sounds in the open world.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/784817895896907846

Original requester: hiru#9397

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by Aireil** [comment]
Doable with Penumbra.
"fileSwaps": {
    "sound/strm/gaya_lestarea_01.scd": "sound/strm/gaya_nosound.scd"
}

**Comment by kalilistic** [comment]
Penumbra or SoundFilter.
