### ISSUE TITLE
Show FC name tag option

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#189]
### Description
Add option to show FC name tags. The game only has party, alliance, other, and friends.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/786055280726376488

Original requester: Lynsis#4220

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
To clarify, they mean they only want to see FC Tags for people in their FC.

**Comment by karashiiro** [comment]
Adding #173 to this.
