### ISSUE TITLE
Hide FC names from nameplates

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#191]
### Description
Hide FC names from nameplates.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/786512668503965716

Original requester: индивидуал#9209

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by Aireil** [comment]
Implemented by Simple Tweaks:

![](https://i.imgur.com/8ebQ2kQ.png)
