### ISSUE TITLE
Remove community finder button

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#197]
### Description
Remove community finder button from the free company, social, and linkshell menus.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/787853145690603551

Original requester: Cordy#1767

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Already part of SimpleTweaks.
