### ISSUE TITLE
Inverse VoidList

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#22]
### Description
An option to only show specific players.

### More info
See https://discordapp.com/channels/581875019861328007/685275026156683280/742733135191605268 for more information.

Original requester: `Soey#0981`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by kalilistic** [comment]
This is in Visibility now.
