### ISSUE TITLE
Separate HP and MP bars

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#223]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/794492953145245726 for more information.

Original requester: ryan#0007

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by SlyAceZeta** [comment]
Done, fulfilled by [Simple Tweaks](https://github.com/Caraxi/SimpleTweaksPlugin) (UI Tweaks > Parameter Bar Adjustments)
