### ISSUE TITLE
Auto translate chat

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#233]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/797104214143926312 for more information.

Original requester: Crow#8945

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Haplo is currently working on. In progress version in Discord text channel plugin_testing_releases

**Comment by Haplo064** [comment]
Aiming for 5.5 for a release

**Comment by kalilistic** [comment]
ChatTranslator plugin.
