### ISSUE TITLE
Keep track of who hasn't rolled on loot

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#237]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/798431133598875650 for more information.

Original requester: Ces#5061

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by kalilistic** [comment]
Kapture tracks who HAS rolled on loot but not the same. I can add this pretty easily once the party API is available.

**Comment by kalilistic** [comment]
Added and is on API4.
