### ISSUE TITLE
Ocean fishing plugin

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#238]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/798616435018170389 for more information.

Original requester: voetre#3694

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by kalilistic** [comment]
Ocean Fishin' got merged.
