### ISSUE TITLE
Change skill names arbitrarily

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#243]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/800022282696523797 for more information.

Original requester: NoNameForEvil#6077

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by NadyaNayme** [comment]
I believe this is handled by [Namingway](https://git.annaclemens.io/ascclemens/Namingway).
