### ISSUE TITLE
Remove targeting functionality from right click

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#247]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/800464691335659521 for more information.

Original requester: tempo#8541

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Already suggested [https://github.com/goatcorp/suggestions/issues/330](url), and already part of simpletweaks
