### ISSUE TITLE
Fetch housing item previews

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#254]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/802681200303931413 for more information.

Original requester: `Ridge#0001`

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by SlyAceZeta** [comment]
From that link:

> `kirby#1208` doesn't the housing system support previews already?
> `Cara#2632` not before you make/buy the item 
> `Ridge#1990` Yea you gotta own the item first ^^

This is available in the game; you can preview indoor or outdoor furnishings and search for almost any furnishing to preview it. I believe the only restrictions are Mog Station items and fixtures.
