### ISSUE TITLE
Cutscene timers

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#256]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/803439040308707350 for more information.

Original requester: KiwiShuriken#0125

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by kalilistic** [comment]
Duplicate https://github.com/goatcorp/suggestions/issues/15
