### ISSUE TITLE
Command aliases

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#27]
### Description
Custom commands/aliases. For example, the ability to set the command /h to mean and execute /tp estate. Could also be used in combination with MacroRecursion's /macro and execute a list of commands.

### More info
Original requester: `ipsumata#0001`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by lmcintyre** [comment]
This is a feature in ST
