### ISSUE TITLE
Blu hot bar sets

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#271]
### Description
For blu, save every active skill sets with its own hotbar setting, so if u change sets u don't need to drag & drop skills from the book every time

### More info
https://discord.com/channels/581875019861328007/685275026156683280/806799566845509672

Original requester: Hans Yolo#6986

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by PunishedPineapple** [comment]
This is a vanilla game feature as of patch 5.5.
