### ISSUE TITLE
Command to open glam plates

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#278]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/807683353322192907

Original requester: Zombie Jesus#0002

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Command already exists `/ac "Glamour Plate"`.
