### ISSUE TITLE
Mount/minion roulette from specific list

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#280]
### Description
Set a specific list of mounts/minions to pick one from at random - you could have multiple sets rather than just one like the vanilla version.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/807697923034972170

Original requester: VariableVixen#8496

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by AmenneHolelane** [comment]
implemented by Qolbar
