### ISSUE TITLE
Disable auto-rotation in controller legacy mode

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#298]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/811443427652403251

Original requester: mobad#7719

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
feature is in the next release of SimpleTweaks
