### ISSUE TITLE
No more rain

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#301]
### Description
See title. Don't change weather though.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/811929691568603146

Original requester: Eternita#4037

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by Eternita-S** [comment]
The plugin is already made, however, it does change weather. I, however, have no intention to make it possible to send invalid data to servers so if it's known that it could result invalid data sending under certain conditions - please let me know and I'll see what is possible to do to prevent it. Even if it doesn't makes the plugin to be allowed to be on official repo, I'll try to make it as safe as possible regardless.

**Comment by karashiiro** [comment]
@goaaats

**Comment by kalilistic** [comment]
Weatherman does this in a safe way now and is on main repo.
