### ISSUE TITLE
Remove pillarbox effect

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#302]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/812129201120477194

Original requester: Vagrant Zero#1006

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by PunishedPineapple** [comment]
Ultrawide Cutscenes plugin addresses this.
