### ISSUE TITLE
Show nearest Ather Current on map when using compass

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#309]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/812545699094200381

Original requester: Seras Victoria 2.0#1997

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Similar to this issue[https://github.com/goatcorp/suggestions/issues/249](url)
