### ISSUE TITLE
Show gathering nodes on normal map like minimap

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#310]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/812622220584157204

Original requester: Lumas#9642

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by gynryiie** [comment]
I actually made a similar suggestion like 8 months earlier:
https://discord.com/channels/581875019861328007/685275026156683280/717134899336970270

but I guess this is irrelevant now with the recent announcement from the live letter
![chrome_VOGdsgnTRm](https://user-images.githubusercontent.com/19721540/113445546-a7d09700-9428-11eb-91f4-1a908ebb7893.png)

**Comment by gynryiie** [comment]
I actually made a similar suggestion like 8 months earlier:
https://discord.com/channels/581875019861328007/685275026156683280/717134899336970270

but I guess this is irrelevant now with the recent announcement from the live letter
![chrome_VOGdsgnTRm](https://user-images.githubusercontent.com/19721540/113445546-a7d09700-9428-11eb-91f4-1a908ebb7893.png)
