### ISSUE TITLE
Target range rings

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#32]
### Description
Configurable rings (like Pixel Perfect does) except around the player's target.

### More info
Original requester: `Memento#0001`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by karashiiro** [comment]
I'm considering [this](https://discordapp.com/channels/581875019861328007/685275026156683280/743202510327775344) to be a duplicate, or close enough to be merged into this.

**Comment by Em-Six** [comment]
I've requested this a few times, so would be super interested in seeing it done.

**Comment by SlyAceZeta** [comment]
Done, fulfilled by [Distance](https://github.com/PunishedPineapple/Distance)
