### ISSUE TITLE
Distance from target

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#328]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/817917840026894368

Original requester: Eternita#4037

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Already suggested [https://github.com/goatcorp/suggestions/issues/167](url)

**Comment by karashiiro** [comment]
#167
