### ISSUE TITLE
Disable targeting players with RMB

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#330]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/818120425186918422

Original requester: Hadesz#1223

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Already part of SimpleTweaks Canary
