### ISSUE TITLE
Show ping/location in status bar

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#331]
### Description
See title. Originally ST request.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/818597889294860300

Original requester: Eternita#4037

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by PunishedPineapple** [comment]
I think this is covered by Ping Plugin and WAIA?
