### ISSUE TITLE
Change dialog text color

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#337]
### Description
Looking for the "system text style" applied top all dialog text.

![unknown1](https://user-images.githubusercontent.com/35899782/113370463-ee8f9580-9331-11eb-8020-f807e1334b7a.png)
![unknown2](https://user-images.githubusercontent.com/35899782/113370467-efc0c280-9331-11eb-990b-5dbeb706b16e.png)

### More info
https://discord.com/channels/581875019861328007/685275026156683280/819580134737838090

Original requester: Talem#0187

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by ascclemens** [comment]
I'm working on this.

**Comment by ascclemens** [comment]
Added in new plugin: Text Box Styler.
