### ISSUE TITLE
Manaticker

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#342]
### Description
Literally just a bar that fills everytime mana is replenished for blm.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/821627253196587009

Original requester: Yunath#7041

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by Haplo064** [comment]
Have the core done.
Trying to make it look pretty.

**Comment by kalilistic** [comment]
Is this still in-progress or should be moved to unclaimed or done?

**Comment by PunishedPineapple** [comment]
Should be covered by MP Tick Bar plugin.
