### ISSUE TITLE
Remove gathering text in middle of screen

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#348]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/823468877371277332

Original requester: ╲⎝⧹Eclair⧸⎠╱#0520

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by ascclemens** [comment]
This can be done using Burnt Toast. `^You obtain .+\.$`
