### ISSUE TITLE
Autohide XP bar at 80

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#350]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/823841476425285662

Original requester: Scarletto#1234

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by daemitus** [comment]
Sounds like a simple tweak

**Comment by kalilistic** [comment]
Requested again: https://discord.com/channels/581875019861328007/685275026156683280/861444090784251935

**Comment by ascclemens** [comment]
Done in ST. Don't think it's on DalamudPlugins yet, but next update.
