### ISSUE TITLE
Show PF party into in chat log

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#351]
### Description
You join X's party. "2 CHEST Quick RECLEAR - Wall relative - JP strat T/H Adjust."

### More info
https://discord.com/channels/581875019861328007/685275026156683280/824126736869883971

Original requester: Mysterious#5425

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by kalilistic** [comment]
Implemented in Better Party Finder.

**Comment by AmenneHolelane** [comment]
only for crossworld parties tho

**Comment by ascclemens** [comment]
Yeah, only for CW parties, but that's like 99% of PF anyway
