### ISSUE TITLE
Move or hide temporary NPC dialogues in duties

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#367]
### Description
A plugin that lets you move or hide the temporary NPC dialogues in duties.

### More info
These dialogues:
![](https://cdn.discordapp.com/attachments/685275026156683280/828307138312929330/unknown.png)

https://discord.com/channels/581875019861328007/685275026156683280/828307141575704616

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by ascclemens** [comment]
This is done in Burnt Toast 1.2.0 (available in 5.5).
