### ISSUE TITLE
Make Alt+Enter toogle fullscreen

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#370]
### Description
See title. Maybe other keybinds too?

### More info
https://discord.com/channels/581875019861328007/685275026156683280/828626539553357875

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by PunishedPineapple** [comment]
Fullscreen Toggle plugin was just added a couple of days ago.
