### ISSUE TITLE
Leave Party Command

### ISSUE THREAD

**Issue by SavvyKam** [goatcorp/suggestions#371]
### Description
Create a chat command to leave the current party you're in (assuming you're not in an instance)

### More info
Preferably, something like /pleave

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by Aireil** [comment]
There's already [/leave](https://eu.finalfantasyxiv.com/lodestone/playguide/db/text_command/53d239d6f98/), what would be the difference?

**Comment by SavvyKam** [comment]
Wow. I really didn't realize that existed. ...how do I delete a thread..

**Comment by Aireil** [comment]
You can just close it :)
