### ISSUE TITLE
Triple Triad Plugin

### ISSUE THREAD

**Issue by SillyEcho** [goatcorp/suggestions#381]
### Description
A plugin that assists the player in winning matches in Triple Triad versus NPCs with the possibility of other related improvements.

### More info
Disables itself for PvP matches.
Suggest best possible move(s) for the current turn, based on the current ruleset (Same, Plus, etc), current deck used, NPC deck.
Suggest deck for specific NPCs (possibly look at data from Triple Triad websites as reference?).

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by kalilistic** [comment]
I think some of the other mini game helpers were still under consideration. So might need goat to weigh in?

**Comment by Aireil** [comment]
Hasn't been merged in months; goat's way of saying no without saying no 5Head

**Comment by daemitus** [comment]
Well now there's a fresh PR he can ignore :D

**Comment by karashiiro** [comment]
Marking this unclaimed in accordance with #387, assuming nobody has any other concerns

**Comment by SillyEcho** [comment]
Has been made by MgAl204, plugin name is Triad Buddy.
