### ISSUE TITLE
Confirmation Skipper

### ISSUE THREAD

**Issue by FortuneSeller** [goatcorp/suggestions#386]
### Description
A plugin to skip annoying confirmation check boxes

### More info
![image](https://user-images.githubusercontent.com/73858921/115431467-a31c2900-a205-11eb-9afc-2055a1faff2d.png)
The plugin would allow the user to configure if it should auto skip confirmation windows like the one above for when you try to buy an item that your class can't equip or when desynthing unique gear.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by reiichi001** [comment]
Automating UI interactions is generally considered not allowed because it has to directly interact with the client program running and "click" them. The server waits for that confirmation, so they cannot be bypassed/skipped without user interaction. 

Per the guidelines,
> b) automatic, as in polling data or making requests without direct interaction from the user which could create unwanted load on the server or give away that XIVLauncher is being used.

**Comment by karashiiro** [comment]
Closing as unsupported unless anyone has a workable way around that.

**Comment by daemitus** [comment]
i already support this in "other" addons

**Comment by daemitus** [comment]
the officially supported way would be to bypass the confirmation window entirely, rather than how I'm doing it though. ala teleporter.

**Comment by karashiiro** [comment]
Sticking a "research needed" on this in case anyone cares to try and find an equivalent function.

**Comment by daemitus** [comment]
So the teleport stuff is in the agent. What I haven't been able to figure
out is how the agent for an agent less add-on is found. It's stored in
rapture somewhere
