### ISSUE TITLE
Autoconnect after disconnect

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#394]
### Description
See title.

### More info
Likely would not be permitted from discussions.
https://discord.com/channels/581875019861328007/685275026156683280/834890892296978442

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by Bluefissure** [comment]
https://github.com/goatcorp/DalamudPlugins/pull/748 seems do the job.

**Comment by kalilistic** [comment]
Released with NoKillPlugin.
