### ISSUE TITLE
Show zone image while loading

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#395]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/834911689719676949

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by lmcintyre** [comment]
The server does not tell the game which zone you are going to until partway through the transition, depending on the type of transport. A workaround could be to show the current zone's loading image when leaving, rather than showing your destination.

**Comment by kalilistic** [comment]
Implemented by Fancy Loading Screens.
