### ISSUE TITLE
Emote aliases

### ISSUE THREAD

**Issue by persecom** [goatcorp/suggestions#397]
### Description
Emote aliases

### More info
Ability to specify an alias for an emote. 
I.e.:
/malevolence -> /curse
/box -> /spar
/tomestone -> /phone

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by Aireil** [comment]
You can alias commands in Simple Tweaks.

**Comment by karashiiro** [comment]
Maybe we need a `simple tweaks` label.
