### ISSUE TITLE
BGM swapper

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#4]
### Description
Don't play certain BGM tracks ever. I'm interpreting this to mean swapping BGM, rather than muting. Originally a suggestion for Orchestrion.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/739882477363134476 for more information.

Original requester: `Aisu#0001`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by Eternita-S** [comment]
Been looking into it, thinking of possibly doing it as an extension to orchestrion plugin via reflection. However that way it will result in a lot of code copying from orchestrion plugin itself and it will be messy and complicated. The real way is to implement it from inside of orchestrion plugin, it's actually really easy

**Comment by Eternita-S** [comment]
https://github.com/Eternita-S/OrchestrionPlugin/releases/tag/Replacer_test
If anyone feels like testing it
Barely tested by me, seems to work though

**Comment by kalilistic** [comment]
Is this still in-progress or should be moved to unclaimed or done?

**Comment by SlyAceZeta** [comment]
Done, fulfilled by [Orchestrion Plugin](https://github.com/lmcintyre/OrchestrionPlugin)
