### ISSUE TITLE
Show time targeted for Peeping Tom

### ISSUE THREAD

**Issue by preachredbull** [goatcorp/suggestions#408]
### Description
Enable a timer for peeping tom to show how long a player has targeted you.

### More info
If a player targets for 1s then it will read Player Name 1s 1:01pm. If the player has targeted past 60s then the ticker would read Player Name 1m9s 1:01pm
----

 - [] I checked if this request wasn't already proposed
 - [] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by kalilistic** [comment]
Closing since this is a request for a specific plugin and should be raised with the plugin author.
