### ISSUE TITLE
Triple triad collection tracker/finder

### ISSUE THREAD

**Issue by FortuneSeller** [goatcorp/suggestions#409]
### Description
A plugin like the /tourist plugin for triple triad card collecting

### More info
Plugin that tracks what cards are missing from the collection and tells you where to get the missing cards and the npc with the cards location and time to duel.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by haojunsui** [comment]
I'm working on this. Possible triple triad solver will be included in the plugin as well

**Comment by MgAl2O4** [comment]
@haojunsui: huh, didn't know that suggestion repo was a thing and just ported my solver (https://github.com/MgAl2O4/FFTriadBuddy) as getting a request for it :D

how far did you get already? let me know if you want to colab or sth

**Comment by kalilistic** [comment]
@MgAl2O4 is this a feature of TriadBuddy and can be closed?

**Comment by MgAl2O4** [comment]
@kalilistic yup, collection browsing, stats, solver, etc
