### ISSUE TITLE
Additional glamour plates

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#42]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/778170501058527252 for more info.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Unlikely because glamour plates are stored server side.

**Comment by goaaats** [comment]
This isn't possible, based on how the game works at the moment
