### ISSUE TITLE
Variable FPS cap by zone

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#420]
### Description
A plugin that allows user-configured FPS caps per zone, for power-saving purposes.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/842534229387771914
`example: im afking in gridania, the fps cap would be autoset to 60-70fps, when im in a savage fight, it could be uncapped or at another present value`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by PunishedPineapple** [comment]
ChillFrames

**Comment by MidoriKami** [comment]
Hell yeah! I implemented #420! Didn't even realize!
