### ISSUE TITLE
A macro for character switch (logout > login)

### ISSUE THREAD

**Issue by Playiku** [goatcorp/suggestions#427]
### Description
A plugin to quickly switch from one character to another.

### More info
For example, I often have to switch characters, one is on Ragnarok and the other is on Moogle. Couldn't a macro make the change for us ?

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by lmcintyre** [comment]
no

**Comment by karashiiro** [comment]
I think this veers too heavily into automation territory - @goaaats can reopen this if he disagrees.
