### ISSUE TITLE
Loot roll management plugin

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#43]
### Description
Loot roll management/monitor(?) plugin, that allows auto-need/greed/pass based on user-provided rules.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by lmcintyre** [comment]
Isn't auto-need/greed/pass breaking the guidelines?

**Comment by kalilistic** [comment]
Based on goat's comments, I think aliasing loot rolling is OK but automatic rolling is not.
https://discord.com/channels/581875019861328007/719513457988337724/815769604537712661
