### ISSUE TITLE
Plugin to see Crit %

### ISSUE THREAD

**Issue by Darkloud91** [goatcorp/suggestions#431]
### Description
Show Stats like Crit with %

### More info
You can here put more technical information, or get more specific.
Feel free to also add context, mockups or anything else here.

----

 - [] I checked if this request wasn't already proposed
 - [] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by PunishedPineapple** [comment]
Character Panel Refined does this.
