### ISSUE TITLE
Hide player names

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#461]
### Description
Plugin to hide player names outside your party during combat, unless they're dead.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/850391158160621579

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by UnknownX7** [comment]
Done, I'll see about adding it to SimpleTweaks tomorrow since I think it would make the most sense.
