### ISSUE TITLE
Hide MP bar

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#469]
### Description
See title. Why need to know MP on some jobs?

### More info
https://discord.com/channels/581875019861328007/685275026156683280/852937555706904607

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by PunishedPineapple** [comment]
Covered by Simple Tweaks "Parameter Bar Adjustments".
