### ISSUE TITLE
Target distance indicator in Yalms

### ISSUE THREAD

**Issue by RisariL** [goatcorp/suggestions#490]
### Description
I guess this has something to do with the circles around the target ? But i would more imagine a indicator in Yalms, to know if i'm in good range for my Dancer dance/melee aoe for example

### More info
It could be close to the target's HP bar, like in Aion, for example where the %hp are
![Screenshot_44](https://user-images.githubusercontent.com/86736478/123999384-bf410100-d9d2-11eb-8bd7-d7a4775be655.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by PunishedPineapple** [comment]
In-progress as the basis for #742.

**Comment by PunishedPineapple** [comment]
"Distance" plugin for this is available in testing.
