### ISSUE TITLE
How much time left before my combo fades ?

### ISSUE THREAD

**Issue by RisariL** [goatcorp/suggestions#491]
### Description
I'd like to know how much time i have left before my combo fades

### More info
Example: WAR needs and the inner release burst during a combo, can I burst AND do the 3rd spell of my combo in time ? Let a countdown tell me, or any indicator

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by NadyaNayme** [comment]
I believe this is solved by Simple Tweaks -> Combo Timer? Shows a countdown for combo actions which will let you know how much time is left before a combo fades.

**Comment by username4447** [comment]
yes now it's outdated and simpletweaks does it \o/
