### ISSUE TITLE
Persistent gear condition and spiritbond overlay

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#51]
### Description
See title.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/739109976794202112 for more information.

Original requester: Hikarin#0208

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by SlyAceZeta** [comment]
Done, fulfilled by [RepairMe](https://github.com/chalkos/RepairMe)
