### ISSUE TITLE
Rename skill names to plain english

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#513]
### Description
Request specifically for SAM but could apply elsewhere.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/863196052249247764

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by PunishedPineapple** [comment]
Probably covered by Namingway?
