### ISSUE TITLE
Change Spell Localization Back To 'Ra' 'Ga' 'Ja'

### ISSUE THREAD

**Issue by kalli-v** [goatcorp/suggestions#526]
### Description
A simple in concept update to how the spells are listed for Black and White Mages to use the semi-traditional suffixes of old. 

### More info
Many, including myself, have always been a little bummed about the nomenclature of spells and how the English localization team went with "1" "2" "3", etc instead of of the suffixes.  I am not a coder by any means so I can't do it myself and I realize that its purely a cosmetic choice but having the suffixes would just make mine and other people's day. 

Fire, Fira, Firaga, Firaja
Blizzard, Blizzara, Blizzaga, Blizzaga
Thunder, Thundera, Thundaga, Thundaja
Cure, Cura, Curaja

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by kalilistic** [comment]
Namingway is on Anna's testing repo.

**Comment by kalilistic** [comment]
Released with Namingway.
