### ISSUE TITLE
Additional chat channels

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#529]
### Description
More than the four by default.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/867312013595901962

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by karashiiro** [comment]
Duplicate of #316
