### ISSUE TITLE
Gridstyle party frame

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#535]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/869882378036842516

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by goofy-somebody** [comment]
Wouldn't this be similar, if not the same as #531

**Comment by karashiiro** [comment]
Indeed, closing.
