### ISSUE TITLE
Allow party list buffs/debuffs to grow to the left

### ISSUE THREAD

**Issue by TelrikRoch** [goatcorp/suggestions#539]
### Description
A mod/plugin to allow the party list buffs/debuffs to grow out to the left.

### More info
This would allow folks to have the party list to the left of their character without the party buffs/debuffs covering anything overly important. Might be personal preference, but could be good for folks with most of their UI on the right and are adjusted to look left for the party list.

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by Caraxi** [comment]
I will add this to Party List Layout

**Comment by kalilistic** [comment]
Closing as is/will be feature of PLL.
