### ISSUE TITLE
Show current zone

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#54]
### Description
Simple plugin that tells you the zone you are currently in.

### More info
Original requester: Lumi#1690

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by lmcintyre** [comment]
Where's WOLdo was made for this suggestion iirc
