### ISSUE TITLE
Ready Check Tracker

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#550]
### Description
A persistent ready check tracker that shows the results of the check after it concludes.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/873843794813022239

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by karashiiro** [comment]
Edited to include a description, since it was a bit too vague from the title alone.

**Comment by PunishedPineapple** [comment]
FWIW, I had this partially figured out a few months ago, and just mostly had some issues with party list ordering stuff.  I'll update what I had to API 4 and give it another shot in the coming weeks I guess.

**Comment by PunishedPineapple** [comment]
Submitted a PR for this to testing a few days ago.  https://github.com/PunishedPineapple/ReadyCheckHelper
