### ISSUE TITLE
Server Tick / MP tick

### ISSUE THREAD

**Issue by Hypn0tyk** [goatcorp/suggestions#552]
### Description
A simple server tick/mp tick plugin

### More info
Display the server tick/mp tick with a small visual indicator.  
There are lots of ways to display this, but either a linear or radial progress indicator that clears each tick would work pretty well.
Options for resize, position etc. to fit in with the UI.  Might be good to make it fit in visually with the MP bar.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by chalkos** [comment]
Already exists: https://github.com/talimity/mptimer
It is in testing on the main repo.
