### ISSUE TITLE
Show gcd circle on cursor

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#557]
### Description
![5fa7e2849cb63f6c6710bc8d](https://user-images.githubusercontent.com/35899782/130326780-600af314-ea29-4128-8a80-2035fc5e5e7d.gif)

### More info
https://discord.com/channels/581875019861328007/685275026156683280/876510155024515082

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by nyxalteria** [comment]
think this can be closed, it was added to simple tweaks
