### ISSUE TITLE
Musical instrument selection UI dedicated to PERFORM

### ISSUE THREAD

**Issue by torakiti2017** [goatcorp/suggestions#579]
### Description
A plug-in that adds an instrument selection UI dedicated to PERFORM.

### More info
It is very inconvenient to switch to another instrument while playing an instrument. (It is necessary to bother to cancel the playing state)
You need a way to switch to another instrument with just one click.
With the current specifications
(1) Cancel the performance once and select the action of each instrument from "My character" → "Action list" → "PERFORM".
(2) Cancel the performance once and select the action of each instrument set in the hot bar.

There are various means, but all have disadvantages.
(1) It takes time and effort.
(2) The precious hot bar space is filled with musical instrument actions.

By adding a new instrument selection UI and selecting an instrument action from that UI during performance (even when not playing)
It would be great to be able to switch to another instrument.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by MgAl2O4** [comment]
Working on bard performance assist right now, can add this to feature list. 
Sounds like a simple macro fired from plugin's UI (press Esc, wait, press instrument action) so I think it's within Dalamud rules?

**Comment by torakiti2017** [comment]
I want such a feature!
I thought it was within the rules because it was possible for the player to do it in the usual way.

**Comment by akira0245** [comment]
@torakiti2017  instrument selection command is already a part of midibard.
