### ISSUE TITLE
Add Bicolor Gemstones to currency tab

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#580]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/884484797341249546

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by AncientAzem** [comment]
As of 6.1 this is no longer something that would need to be done via plugin as it is a native feature now 😌
