### ISSUE TITLE
What you guys think of a plugin to maintain tank stance on with levelsync?

### ISSUE THREAD

**Issue by Nitzowsky** [goatcorp/suggestions#586]
### Description
A plugin to maintain tank stance on with levelsync

### More info
When you levelsync in a fate or dungeon the tank stance is always off.
There is a way to create a plugin to maintain the stance on?

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by Eternita-S** [comment]
was previously proposed and was previously disallowed

**Comment by johnysandels** [comment]
I think it would be a nice QoL feature. I don't see it giving the player an advantage, and it would work in a similar way to how AutoVisor works, where it uses a command when the condition is met.

**Comment by kalilistic** [comment]
I remember this being discussed too and I think the concern was around the automatic rule.
_b) automatic, as in polling data or making requests without direct interaction from the user which could create unwanted load on the server or give away that XIVLauncher is being used._
