### ISSUE TITLE
In-game battery indicator

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#600]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/891897610783297546

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by KazWolfe** [comment]
Gonna take a look at this one this week and see what's possible!

**Comment by kalilistic** [comment]
Check out BatteryGauge by @KazWolfe!
