### ISSUE TITLE
Show gil in inventory window

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#610]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/896398910732513320

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by Caraxi** [comment]
Simple Tweaks now has this
