### ISSUE TITLE
Show item prices on market board without having to click

### ISSUE THREAD

**Issue by ercarp** [goatcorp/suggestions#615]
### Description
A plugin for displaying an item's lowest price on the market board without having to click on it.

### More info

When looking up items on the market board, I often get frustrated having to click individually on each item to get an idea of the price range. Veteran players likely have a better idea of how much everything costs, but newer players like myself have no clue.

Adding a new column to the left of the quantity number displaying the lowest price the item is currently being sold at would be a life-saver for many (if it's within the realm of possibilities).

**Mockup**
![image](https://user-images.githubusercontent.com/78575425/137585336-16a80e50-0b46-48ec-a81a-e56167646b0c.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by ackwell** [comment]
Unfortunately, fetching _any_ price information for an item requires sending an additional request to the server:

![image](https://user-images.githubusercontent.com/534235/137585644-33b964c3-04f4-4e39-907b-bd163a034316.png)

Blue is client -> server. Yellow is server -> client.

Dalamud plugins will not send requests to the server. This won't be implemented.

**Comment by ercarp** [comment]
> Dalamud plugins will not send requests to the server. This won't be implemented.

Fair enough. Hopefully, they'll add something like this to the official client someday.
