### ISSUE TITLE
Deathrolling

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#621]
### Description
Check dice rolls in game, the ones we do in say or party chat. Have it check for highest, lowest rolls or closest to whatever number we pick.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/900579414499295242

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by Infiziert90** [comment]
i would like to work on this one

**Comment by Infiziert90** [comment]
PR for testing release:
goatcorp/DalamudPlugins/pull/2556

**Comment by Infiziert90** [comment]
PR got merged, so this can be closed
