### ISSUE TITLE
Lock UI elements like loot window

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#625]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/901902730715615233

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by lmcintyre** [comment]
Closable with ST 1.6.3.0
