### ISSUE TITLE
real time memory usage of installed plugins

### ISSUE THREAD

**Issue by ManiaMoo** [goatcorp/suggestions#633]
Pretty simple and self explanatory!
Cursor over an icon or type /memusage or similar to access a menu that checks the memory usage of each plugin/sorts by highest to lowest.
Good for developers to check for leaks or odd spikes in usage, could graph usage potentially?
Useful for players who notice slowdown since installing too many plugins too!

**Comment by Eternita-S** [comment]
Seems like you just need a .net profiler

**Comment by ManiaMoo** [comment]
> Seems like you just need a .net profiler

I do keep track of my own stuff, but more so for general users. I think back to people lagging on wow only to find out recount was using 50-100mb and some quest guide plugin was using another 100+

**Comment by Caraxi** [comment]
Fairly sure its not possible to determine how much memory each plugin is using

**Comment by kalilistic** [comment]
Total memory was added to dalamud. Probably enhancement on this would be a suggestion on the dalamud repo rather than plugin specific.
