### ISSUE TITLE
Show DC in Title Menu

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#654]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/910658081350877214

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by Soreepeong** [comment]
Really budget method but https://github.com/goatcorp/DalamudPlugins/pull/1508 should give you what this user wanted.


![screencap1.png](https://raw.githubusercontent.com/Soreepeong/QuoteOfTheLobby/main/Data/screencap1.png)
![screencap2.png](https://raw.githubusercontent.com/Soreepeong/QuoteOfTheLobby/main/Data/screencap2.png)
