### ISSUE TITLE
Queue notification

### ISSUE THREAD

**Issue by Phalk** [goatcorp/suggestions#671]
### Description
A plugin to show queue position on update or a 2002 error if it ocurred as a windows notification.

### More info
Not much info needed. Just a plugin to show queue position or 2002 error as a notification on windows while the game's in the background.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by bpartridge** [comment]
Related: if this could also be made to call a webhook, we could use various utilities like pushsafer.com to turn this into mobile push notifications, letting us know to come back to our computers when the queue pops! More vital than ever now that savages are out!

**Comment by avafloww** [comment]
This now exists in the form of Waitingway, available on the official plugin repo.
