### ISSUE TITLE
Aether currents on Map/Minimap

### ISSUE THREAD

**Issue by Ashensakar** [goatcorp/suggestions#672]
### Description
a plugin that places a dot/icon on the map of where an Aether current is.

### More info
People have been using maps from guides/websites to find these, i think there should be a plugin to just put it on your map for you as a guide, so no needing to tab back and forward 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by kalilistic** [comment]
Duplicate: https://github.com/goatcorp/suggestions/issues/249
