### ISSUE TITLE
Re-initialise Audio Output

### ISSUE THREAD

**Issue by mmonaghan** [goatcorp/suggestions#677]
### Description
The plugin would allow the user to reinitialise the game's audio output on demand, be it via a chat command or a button

### More info
To minimise inconvenience caused by the game's audio output just completely breaking, which as to present I've only managed to restore functionality via a game relaunch, assuming it's feasible to do so, the plugin would reload the audio engine so as to restore the game's audio without requiring a game relaunch and being once again faced with Queues (Ultimate). 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by kalilistic** [comment]
Can use the ResetAudio plugin.
