### ISSUE TITLE
Variable frame limiter based on zone

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#68]
### Description
See title.

### More info
See https://discordapp.com/channels/581875019861328007/685275026156683280/747555359035621466 for more information.

Original requester: Mazel Col#5839

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by karashiiro** [comment]
Adding https://discord.com/channels/581875019861328007/685275026156683280/803343058174214204 to this.

**Comment by PunishedPineapple** [comment]
Probably resolved by ChillFrames.
