### ISSUE TITLE
Queue Estimate

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#685]
### Description
Estimate when you'll get in.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/919371171072450640

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by avafloww** [comment]
I'm working on a plugin for this currently (tentatively named XIVq).

**Comment by avafloww** [comment]
2022 update: this will be a feature coming to Waitingway in the near future. Waitingway is now available on the official plugin repo.
