### ISSUE TITLE
Mahjong helper

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#703]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/920647730664206386

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by Bluefissure** [comment]
Would be easier if connecting it to https://github.com/EndlessCheng/mahjong-helper since most of the rules are the same.

**Comment by goaaats** [comment]
Mahjong in XIV is purely PvP, there's no SP rewards, so this would purely be used to cheat in rankings
