### ISSUE TITLE
Add custom text to retainers

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#716]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/921439900274950195

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by kalilistic** [comment]
Isn't this vanilla now?

**Comment by AncientAzem** [comment]
> Isn't this vanilla now?

It is! You can add up to a 90 character and two line comment to each retainer which displays in the retainer menu when hovering over them
![image](https://user-images.githubusercontent.com/10831565/166091553-a5d3e78f-8773-460d-9665-edcb9fa3dbbd.png)
