### ISSUE TITLE
Lowest-durability gauge

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#73]
### Description
Plugin that shows the percentage of your most-damaged piece of gear.

### More info
See https://discordapp.com/channels/581875019861328007/685275026156683280/749450909972430920 for more information.

Original requester: VariableVixen#7863

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by chalkos** [comment]
I'll take this one. It is an idea that i've thought of before as well.

**Comment by chalkos** [comment]
It is a whole lot of empty for now, but I'll be publishing it here https://github.com/chalkos/RepairMe

**Comment by kalilistic** [comment]
RepairMe was released.
