### ISSUE TITLE
Simple Tweak - Facepull Alert

### ISSUE THREAD

**Issue by Diorik** [goatcorp/suggestions#742]
### Description
A small indicator to show that you're at the standard 15y maximum before most raid bosses face pull.

### More info
It looks like no one has picked up the requests for a dedicated range display, however, tracking a fixed 15y should be a little easier, since you can use Geirskogul's range requirement. Simply, this plugin/tweak would check if you're out of combat, in a duty, and have a target - and then it would see if Geirskogul is able to fire. If all of those are true, some small customizable indicator should pop up letting you know you're as close as you can get before face pulling.

You can achieve similar results in game by using /micon Geirskogul on a dummy macro, the range indicator will be red until you are close enough to use the skill, even if you are not on DRG.

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by PunishedPineapple** [comment]
For what little it's worth, this would be a pretty inaccurate way to track that.  Bosses with larger hitboxes you can get much closer than GK range, sometimes even touching them.  I think standard aggro range is something like 14y from the boss's actual location (center), but even that seems to vary enough that you can't just assume it on a given random boss.

**Comment by Diorik** [comment]
It's what's recommended on Balance as the best available tool. It's not a secret that it isn't 100% reliable.

**Comment by PunishedPineapple** [comment]
I'll take a stab at this as part of a general distance plugin (since I don't see one that's not just "use Compass or DelvUI").  Will probably just keep a database of known aggro ranges, and then use a default for anything it doesn't know.

**Comment by PunishedPineapple** [comment]
The "Distance" plugin is now available in testing and shows this distance for most trial/raid bosses.
