### ISSUE TITLE
Transparent skill icons when level sync'd

### ISSUE THREAD

**Issue by Muddr** [goatcorp/suggestions#750]
### Description
Make the icons for skills that are locked due to being level synced transparent. Would make it easier to see at a glance which is available and just not proc'd verse being sync'd. 

### More info
Mockup example Image for lvl65 dungeon.
 - Left: Available to use.
 - Middle: Disabled due to being level synced.
 - Right: Available, just not proc'd

![image](https://user-images.githubusercontent.com/1361860/147371864-a63856c6-3154-4f3c-a822-82fc602ea941.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by kalilistic** [comment]
Check out KitchenSync. https://github.com/MidoriKami/KitchenSync
