### ISSUE TITLE
Notifications for getting list items

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#76]
### Description
A plugin that would notify you when you/your party has found an item from a list the user makes/maintains, whether it be from a raid drop, dungeon drop etc. Notification would be audio or visual...or both? Useful for Glamour hunting.

### More info
Original requester: Lumi#1690

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by kalilistic** [comment]
Added and is on API4.
