### ISSUE TITLE
Auto-Face Targets off for beneficial spells, on for damaging spells

### ISSUE THREAD

**Issue by Faln987** [goatcorp/suggestions#767]
### Description
What I'm looking for is either a setup where I specify which spells do not auto-face me to the target (heals) or something that automatically just puts all damaging abilities as auto-face and all non-damaging abilities as not auto-face on the target.

### More info
There was a plugin made to make spells/abilities mouseovers when added to a 'stack'. This addon was great because it let me not have to use my mouseover macros anymore for healing. However, I still have to have macros for damage spells set to auto-face the target because I turn the auto-face off for healing (So I can heal while I move and not pull a 180 while getting out of a mechanic.)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by cc12138030** [comment]
This is already proposed in #349

**Comment by kalilistic** [comment]
Closing as duplicate.
