### ISSUE TITLE
Add copy item name command

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#776]
### Description
See title. More places than currently available.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/930279873149284413

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by johnysandels** [comment]
I'm pretty sure this is already part of simple tweaks! You can do a keyboard combo to copy the item name.

**Comment by Nillinn** [comment]
Ctrl+C when hovering an item, with one Simple Tweak activated, yup. (I forgot the name of the tweak)

**Comment by kalilistic** [comment]
See simple tweaks.
