### ISSUE TITLE
Dalamud progress bar

### ISSUE THREAD

**Issue by Purple4789** [goatcorp/suggestions#785]
Could you please add a progress bar showing the amount of MBs and speed are needed to download durning updating assets. This is due to having an extremely low internet speed and tight on time.

**Comment by kalilistic** [comment]
Thanks for raising a ticket - but this repo is only for plugin suggestions. Launcher and Dalamud suggestions should be raised on their respective repos.

https://github.com/goatcorp/FFXIVQuickLauncher
https://github.com/goatcorp/Dalamud
