### ISSUE TITLE
Server UI Concatenator (or something)

### ISSUE THREAD

**Issue by CerbStarraiser** [goatcorp/suggestions#786]
We're starting to get a few plugins that can add info into the Server Info line (where clock is and such).  It seems there's a limitation though where only one thing can be put in.  Perhaps either a plugin (or a feature of Dalamud itself) can be put together, so that anything wanting to drop into into Server UI can pass it to that, then that plugin/feature concatenates it or whatever and is the "one thing" that goes there.

**Comment by kalilistic** [comment]
I think perch looked this as a dalamud feature but got a little complicated and was dropped iirc.

**Comment by kalilistic** [comment]
I think we can close this ticket as it's likely going to be a dalamud feature. There's an open discussion here: https://github.com/goatcorp/Dalamud/discussions/606.
