### ISSUE TITLE
HUD customization with deltas

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#8]
### Description
HUD management plugin that supports deltas, so it only updates specific parts of the ui from the default hud layout. This would make it much easier to have multiple similar layouts and not have to update them individually whenever you make a change.

### More info
See https://discord.com/channels/581875019861328007/685275026156683280/755946886481051719 for more information.

Original requester: `ash#5251`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
HUD Manager has this!
