### ISSUE TITLE
mini map zoom further out

### ISSUE THREAD

**Issue by KawaFoxx** [goatcorp/suggestions#822]
### Description
just simply letting you zoom the mini map further out

### More info
it's pretty simple but I have no idea how hard it would be to make. I'd really enjoy if this was a thing, I don't like opening the big map

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by Eternita-S** [comment]
![20cc556665644b5a3de3af2ecd007a98 1](https://user-images.githubusercontent.com/5073202/155108327-10d78d55-5611-4af0-931f-e1ac2e8a8e7a.jpg)
