### ISSUE TITLE
https://github.com/cairthenn/Redirect

### ISSUE THREAD

**Issue by juiposa** [goatcorp/suggestions#823]
### Description
https://github.com/cairthenn/Redirect
A mouse over plugin with a significantly better user experience than that of the currently included MOActions.

### More info
Can add ordered priorities for each ability on what it'll cast on, in a similar manner to MOAction's stacks. Configuration menu is miles better and easier to use in setting that up than MOAction's is. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by lmcintyre** [comment]
The suggestions repository is not for you to advertise your plugin.

**Comment by juiposa** [comment]
> The suggestions repository is not for you to advertise your plugin.

This isn't my plugin.

**Comment by lmcintyre** [comment]
Very much literally besides the point.

**Comment by juiposa** [comment]
Im not sure how it is, it's not mine, so I'm not advertising it. I misunderstood the use of this repo. 

I'll see about trying to contact the dev.
