### ISSUE TITLE
For XIVCombo Reaper: Replace 'Arcane Circle' with 'Plentiful Harvest' 

### ISSUE THREAD

**Issue by Yalessa** [goatcorp/suggestions#825]
### Description
Since 'Arcane Circle' has a 2 min cooldown and triggers the button for 'Plentiful Harvest', why not replace 'Arcane Circle' with 'Plentiful Harvest' until you pressed it. You can't use 'Plentiful Harvest' without pressing 'Arcane Circle' before anyway and they have different cooldown timers, so I believe it would be no problem :) I'm sure it would come in handy for some people :)

Thanks a lot for considering it, if it get's done, I'll be sure to use it and be happy about it :D
----

 - [] I checked if this request wasn't already proposed
 - [] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by kalilistic** [comment]
Thanks for making an issue, however, this repo is just for new plugin ideas. Please open an issue on the specific plugin repo for new features. Since this is XIVCombo, be sure to read this first though: https://github.com/attickdoor/XIVComboPlugin/issues/119 and review existing open issues.
