### ISSUE TITLE
Show NPC messages in chat log

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#862]
### Description
See title.

### More info
https://discord.com/channels/581875019861328007/685275026156683280/947733467775516692

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by PunishedPineapple** [comment]
I'll take a look at this.  Should be really simple.

**Comment by PunishedPineapple** [comment]
The "Say What?" plugin is now out of testing.
