### ISSUE TITLE
Chat Alerts > Cooldown before the same alert is triggered

### ISSUE THREAD

**Issue by laillearda** [goatcorp/suggestions#868]
### Description
For ChatAlerts can there be an enhancement, basically a default cooldown period, maybe 10secs which can be adjusted. 
This will prevent the same ChatAlert filter from being triggered again, within that period of time. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by kalilistic** [comment]
Thanks for opening a ticket. This repo is only used for new plugins - please raise this on the plugin's github or the suggestions channel in discord.

**Comment by kalilistic** [comment]
By the way, currently maintained by Otter so can use the issues here: https://github.com/Ottermandias/ChatAlerts

**Comment by laillearda** [comment]
Thank you!
