### ISSUE TITLE
Restart audio engine

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/suggestions#886]
### Description
A plugin that restarts the audio engine so you don't have to restart the game (e.g. for when the ucob bug breaks your audio).

### More info
https://discord.com/channels/581875019861328007/685275026156683280/958038826939482122

----

 - [ ] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by kalilistic** [comment]
Is this still an issue? Thought they resolved at least some of the audio issues that required restarts.

**Comment by PunishedPineapple** [comment]
Audio definitely still completely goes away sometimes.  For me, you'll hear a pop, and then nothing from game until you've restarted it.  I usually get this once or twice a month, so it's not a huge deal (and queues being short now makes it whatever too), but I would definitely use a feature like this if it were implemented.

**Comment by Xerlith** [comment]
I can confirm the audio still randomly cuts off. Sometimes very often. Seems to happen very randomly, though. I haven't had it happen for weeks, then suddenly it goes off.

Other people, on the other hand, have it happen once every 1-2 days.

**Comment by nikroulah** [comment]
+1 on this, when I originally suggested this it was to alleviate a quite niche occurrence (rare bug in ucob which cuts audio and requires a game restart). Now it's a semi-frequent occurrence in the new PVP (not sure if it happens in FL, have only experienced it in CC), sometimes multiple times within an hour.

Would be nice to have a plugin to bring audio back without restarting the game.

**Comment by goaaats** [comment]
This happens a lot to me in PvP too, and I've looked into it a little bit, seems non-trivial though.

**Comment by Zeffuro** [comment]
Happened to me as well yesterday, still very much a thing.

**Comment by Rueby** [comment]
Happens often in PvP for me, it's not common outside but happens every now and then....I think this'd be nice to have!

**Comment by kalilistic** [comment]
Can use the ResetAudio plugin.
