### ISSUE TITLE
Crystalline Conflict free chat

### ISSUE THREAD

**Issue by Lukkies** [goatcorp/suggestions#896]
### Description
First i need to clarify that i dont know anything about plugins and much less how they interact with the game, so i understand if this is beyond impossible. The Crystalline Conflict (The new pvp mode added in patch 6,1) have a chat locked, and the only way to communicate is by quick chat messages provided by the game, so a plugin that allows free chat would be very helpful.

### More info
Simply putting, just a way to chat with teammates freely, however, simply unlocking the chat rightaway and allowing everyone in the team to see your messages would be a guaranteed report, so to prevent this, i would suggest a chat mode that is only visible to players using the plugin and are in your team, and at the start of the match you would receive a notification saying how many (if any) players are using the plugin are present in your team (So would be something like "3 players using CChat"), but without revealing who they are to keep their privacy if they so choose. Yes, thats a issue that will hopefully be changed by the devs in future patches, but in anycase, the suggestion remains.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by Caraxi** [comment]
no
