### ISSUE TITLE
Sell to vendor hotkey

### ISSUE THREAD

**Issue by owopeachy** [goatcorp/suggestions#928]
### Plugin Description

suggestion: a sinple tweak Whereby Holding shift/alt/ctrl and clicking on the item automatically sells it as if you clicked sell on the context menu when you have the vendor window open 

### Request Terms

- [X] I checked if this request wasn't already proposed
- [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by Caraxi** [comment]
I can maybe do this in simple tweaks

**Comment by Caraxi** [comment]
Added with Simple Tweaks 1.7
