### ISSUE TITLE
Make target's HP bar display their hp% with decimal precision

### ISSUE THREAD

**Issue by ifindtheway** [goatcorp/suggestions#936]
### Plugin Description

Mimic the functionality of the "/e \<thpp>" macro.

### More info

https://discord.com/channels/581875019861328007/685275026156683280/974695347651743815
Something like this: ![Untitled](https://user-images.githubusercontent.com/38815801/168321682-93c08d57-1b06-4a51-ac30-250c48800231.png)

It would be really helpful for figuring out when certain bosses phase, especially in solo content like old duties and potd

### Request Terms

- [x] I checked if this request wasn't already proposed
- [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by PunishedPineapple** [comment]
Duplicate of #445.
