### ISSUE TITLE
Hide Cross Hotbar when Out of Combat

### ISSUE THREAD

**Issue by roboSTERNE** [goatcorp/suggestions#950]
### Plugin Description

Pre-Existing UI options are insufficient in this regard. Conditional hiding of the Cross Hot Bar would be preferred. 

**Condition 1:** 
In-Combat / Active Duty _(e.g. fate, dungeon)_
**XHB Status:** 
Permanent Display 

**Condition 2:** 
Out-of-Combat / Out-of-Duty
**XHB Status:** _(mimic current "hiding" option)_
Hidden until engaged / interacted with 

### More info

Engaging with the XHB is when a trigger is hit on the controller. The XHB becomes "active" (i.e. highlighted and interactable). With in-game settings, the XHB can remain hidden until a trigger is engaged. This is what should be mimicked in condition 2. 

### Request Terms

- [X] I checked if this request wasn't already proposed
- [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by ArcaneDisgea** [comment]
Hello!

Thank you for your suggestion I noticed this was sent as feedback for crossup as well. This repository is primarily for suggestions for _new_ plugins. For plugins that already exist, you should make an issue on their repository. The crossup repository can be found here, https://github.com/ItsBexy/CrossUp/issues.

Thank you again and have a great day!
