### ISSUE TITLE
Show notification when friends log in

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#96]
### Description
Show in chat when your friends log in like it already shows your fc members.

### More info
Friendlist has to be requested by the server when you open the window.
See https://discord.com/channels/581875019861328007/685275026156683280/760212455787462657 for more information.

Original requester: `ash#5251`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by johnysandels** [comment]
Friendlist has to be requested by the server when you open the window. Can't be done.
