### ISSUE TITLE
Exporting Supply & Demand from Island Sanctuary to Excel or similar tools

### ISSUE THREAD

**Issue by Dysfonction** [goatcorp/suggestions#963]
### Plugin Description

Was wondering whether it was possible to export the supply & demand into a calculation tool since it is personal (not everyone has the same), then Excel could help calculate what the best options are easily.

![image](https://user-images.githubusercontent.com/32390577/187025431-35129f60-65d2-4cee-b1a4-663cafa664b7.png)

### Request Terms

- [X] I checked if this request wasn't already proposed
- [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by kalilistic** [comment]
See AutoMammet.
