### ISSUE TITLE
Whenever Entering/Leaving the game, play an automated text in selected chat/FC Chat

### ISSUE THREAD

**Issue by PLord84** [goatcorp/suggestions#981]
### Plugin Description

Would be sent to the Fc chat whenever entering the game and leaving. 

### More info

Example:
Me: Hello All, hope you have a great day 
Me: Bye Bye, have a great day.

### Request Terms

- [X] I checked if this request wasn't already proposed
- [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by NotNite** [comment]
This doesn't follow our plugin guidelines:

`b) automatic, as in polling data or making requests without direct interaction from the user which could create unwanted load on the server or give away that XIVLauncher is being used.`

**Comment by PLord84** [comment]
> This doesn't follow our plugin guidelines:
> 
> `b) automatic, as in polling data or making requests without direct interaction from the user which could create unwanted load on the server or give away that XIVLauncher is being used.`

Sorry, have a great day and thank you.
