### ISSUE TITLE
Faster Estate Teleportation

### ISSUE THREAD

**Issue by KataLystTB** [goatcorp/suggestions#988]
### Plugin Description

Just wondering if its technically possible to move the Estate Teleportation option from rightclicking a character in the overworld/friend list to the chat rightclick menu, to enable teleporting to a friends plots without opening the friend list or targetting their character in the world.

![image](https://user-images.githubusercontent.com/28195734/212567821-e2bce8a1-f40c-4c9a-8088-bc62f65cd50e.png)

Ideally something like this, for example;
![image](https://user-images.githubusercontent.com/28195734/212567982-c74c0f0c-c5f8-4e2d-907d-d87668db3913.png)

### Request Terms

- [X] I checked if this request wasn't already proposed
- [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by NotNite** [comment]
AFAIK this data isn't sent to the client until you click on the estate teleportation menu. Sending the packet to request data might be detectable.

**Comment by KataLystTB** [comment]
Unfortunate but figured it might be the case, thanks for the response!
